%%% Display setting and output setup
scr = get(groot,'ScreenSize');                              % screen resolution
phi = (1 + sqrt(5))/2;
ratio = 1.5*phi/3;
offset = [ scr(3)/8 scr(4)/8]; 
fig1 =  figure('Position',...                               % draw figure
        [offset(1) offset(2) scr(3)*ratio scr(4)*ratio]);
set(fig1,'numbertitle','off',...                            % Give figure useful title
        'name','Lab 3 - Exercise 1b',...
        'Color','white',...
        'Units','normalized',...
        'visible','off');
fontName='Helvetica';
set(0,'defaultAxesFontName', fontName);                     % Make fonts pretty
set(0,'defaultTextFontName', fontName);
set(groot,'FixedWidthFontName', 'ElroNet Monospace')  

%% Colors and formatting
nice_blue =     [ 0.180     0.180     0.900     0.6 ];
nice_green =    [ 0.180     0.900     0.180     0.6 ];
nice_cyan =     [ 0.180     0.900     0.900     0.6 ];
nice_yellow =   [ 0.900     0.900     0.180     0.6 ];
nice_red =      [ 0.900     0.180     0.180     0.6 ];
pastel_blue =   [ 0.0000    0.4470    0.7410    0.8 ];
trans_blue =    [ 0.0000    0.4470    0.7410    0.15 ];
pastel_orange = [ 0.8500    0.3250    0.0980    0.8 ];
pastel_yellow = [ 0.9290    0.6940    0.1250    0.8 ];
pastel_purple = [ 0.4940    0.1840    0.5560    0.8 ];
pastel_green =  [ 0.4660    0.6740    0.1880    0.8 ];
sky_blue =      [ 0.3010    0.7450    0.9330    0.8 ];
brick_red =     [ 0.6350    0.0780    0.1840    0.8 ];
                    
line_thin = 1;
line_thick = 2;
marker_size = 4;
scale_y = 1.2;
offset_x = 0.025;
offset_y = 0.01;
marker_size = 0.001;
x_entry = floor(numel(message)*.875);

%% Plot setup
subplot_row = 2;
subplot_col = 3;
subplot_entries = subplot_row*subplot_col;


%% Plot 1 (Message signal)
ax1 = subplot(subplot_row,subplot_col,1);
hold on;

p1 = plot(tm(1:x_entry),message(1:x_entry),...
    'Color',pastel_blue,... 
    'DisplayName','m(t)',...
 	'LineStyle','-',...
	'LineWidth',line_thick);
hold on

% Title and Annotations
if ~export_on
    t1 = title({strcat("Message Signal ", p1.DisplayName); " "});
end

% Axes and labels
ylabel(strcat(p1.DisplayName,' \rightarrow'),...
    'FontName',fontName,...
    'FontSize',14);
xlabel({'t \rightarrow','[ms]'},...
    'FontName',fontName,...
    'FontSize',14);

y_lim_1 = [-2 2]*scale_y;
x_lim_1 = [0 tm(end)]*1.05;
set(ax1,...
    'FontSize',12,...
    'Box','off',...
    'XAxisLocation','origin',...
    'YMinorTick','off',...
    'XMinorTick','off',...
    'TickDir','both',...
    'TickLabelInterpreter','tex',...
    'YLim',y_lim_1,...
    'XLim',x_lim_1,...
    'XTick',[0: tm(end)/8 :tm(end)]);
ax1.XAxis.SecondaryLabel.Units='normalized';
ax1.XAxis.SecondaryLabel.Position = [0.9 0.4 0];
ax1.Position = FillAxesPos(ax1,1.1);

%% Plot 2 (Modulated output)
ax2 = subplot(subplot_row,subplot_col,2);
hold on;

p2 = plot(tm(1:x_entry),mixed_signal(1:x_entry),...
    'Color',trans_blue,... 
    'DisplayName','e(t)',...
 	'LineStyle','-',...
	'LineWidth',line_thin);
hold on

p2_a = plot(tm(1:x_entry),envelope1(1:x_entry),...
    'Color',nice_red,... 
    'DisplayName','Upper envelope',...
	'LineStyle','--',...
	'LineWidth',line_thick);
hold on

% Title and Annotations
% if ~export_on
%     t2 = title({strcat("Mixed Signal ", p2.DisplayName); " "});
% end

% Axes and labels
ylabel(strcat(p2.DisplayName,' \rightarrow'),...
    'FontName',fontName,...
    'FontSize',14);
xlabel({'t \rightarrow','[ms]'},...
    'FontName',fontName,...
    'FontSize',14);

y_lim_2 = [-0.5 ceil(max(mixed_signal))]*scale_y;
x_lim_2 = [0 tm(end)]*1.05;
set(ax2,...
    'FontSize',12,...
    'Box','off',...
    'XAxisLocation','origin',...
    'YMinorTick','off',...
    'XMinorTick','off',...
    'TickDir','both',...
    'TickLabelInterpreter','tex',...
    'YLim',y_lim_2,...
    'XLim',x_lim_2,...
    'XTick',[0: tm(end)/8 :tm(end)]);
ax2.XAxis.SecondaryLabel.Units='normalized';
ax2.XAxis.SecondaryLabel.Position = [0.972 0.35 0];
ax2.Position = FillAxesPos(ax2,1.1);


%% Plot 3 (Demodulated output)
ax3 = subplot(subplot_row,subplot_col,3);
hold on;

offset_3 = 20;
x_entry_3 = [offset_3:x_entry-offset_3];

p3 = plot(tm(x_entry_3),demodulated_signal(x_entry_3),...
    'Color',pastel_blue,... 
    'DisplayName','y(t)',...
 	'LineStyle','-',...
	'LineWidth',line_thick);
hold on

p3_b = plot(tm(x_entry_3),filtered_signal(x_entry_3),...
    'Color',nice_red,... 
    'DisplayName','m(t)',...
 	'LineStyle','-',...
	'LineWidth',line_thick);
hold on

% Title and Annotations
if ~export_on
    t3 = title({strcat("Demodulated Signal ", p3.DisplayName); " "});
end

legend3 = legend(ax3,{'$y(t)$','$\hat{m}(t)$'},'Interpreter','latex');
% legend3 = legend(ax3,'show');
set(legend3,... 
    'Location','south',...
    'Orientation','horizontal',...
    'Box','off');

% Axes and labels
ylabel(strcat(p3.DisplayName,' \rightarrow'),...
    'FontName',fontName,...
    'FontSize',14);
xlabel({'t \rightarrow','[ms]'},...
    'FontName',fontName,...
    'FontSize',14);

% y_lim_3 = [floor(min(demodulated_signal)) ceil(max(demodulated_signal))]*scale_y;
y_lim_3 = y_lim_1;
x_lim_3 = [0 tm(end)]*1.05;
set(ax3,...
    'FontSize',12,...
    'Box','off',...
    'XAxisLocation','origin',...
    'YMinorTick','off',...
    'XMinorTick','off',...
    'TickDir','both',...
    'TickLabelInterpreter','tex',...
    'YLim',y_lim_3,...
    'XLim',x_lim_3,...
    'XTick',[0: tm(end)/8 :tm(end)]);
ax3.XAxis.SecondaryLabel.Units='normalized';
ax3.XAxis.SecondaryLabel.Position = [0.972 0.35 0];
ax3.Position = FillAxesPos(ax3,1.1);

%% Plot 4 (Message signal frequency spectrum)
ax4 = subplot(subplot_row,subplot_col,4);
hold on;

p4 = stem(f,message_frequency,'o',...
    'Color',pastel_blue,... 
    'DisplayName','|M(f)|',...
	'LineStyle','-',...
	'LineWidth',line_thick,...
    'MarkerSize',marker_size,...
    'MarkerFaceColor',pastel_blue(1:3));
hold on

% Title and Annotations
if ~export_on
    t4 = title({strcat("Message signal frequency ", p4.DisplayName); " "});
end

% Axes and labels
ylabel(p4.DisplayName,...
    'FontName',fontName,...
    'FontSize',14);
xlabel({'f \rightarrow','[Hz]'},...
    'FontName',fontName,...
    'FontSize',14);

annotation('arrow',[0.1885 0.1885],...
    [0.428 0.445]);

y_lim_4 = [0 1];
x_lim_4 = [-1.5e3 1.5e3];
set(ax4,...
    'Box','off',...
    'XAxisLocation','origin',...
    'YMinorTick','off',...
    'XMinorTick','off',...
    'TickDir','both',...
    'TickLabelInterpreter','tex',...
    'FontSize',12,...
    'YAxisLocation','origin',...
    'XLim',x_lim_4,...
    'XTick',[-f_m 0 f_m],...
    'YTick',[]);

ax4.XAxis.Label.Units='normalized';
ax4.XAxis.Label.Position = [0.98 0.1 0];
ax4.XAxis.SecondaryLabel.Units='normalized';
ax4.XAxis.SecondaryLabel.Position = [0.999 -0.029 0];

ax4.Position = FillAxesPos(ax4,1.1);

%% Plot 5 (Modulated signal frequency spectrum)
mix_frequency = (A_m/N)  * abs(fftshift((fft(mixed_signal))));
ax5 = subplot(subplot_row,subplot_col,5);
hold on;

p5 = plot(f,mix_frequency,'o',...
    'Color',pastel_blue,... 
    'DisplayName','|E(f)|',...
	'LineStyle','-',...
	'LineWidth',line_thick,...
    'MarkerSize',marker_size,...
    'MarkerFaceColor',pastel_blue(1:3));
hold on

% Title and Annotations
if ~export_on
    t5 = title({strcat("Mixed signal frequency ", p5.DisplayName); " "});
end

% Axes and labels
ylabel(p5.DisplayName,...
    'FontName',fontName,...
    'FontSize',14,...
    'Position',[1995624.520,0.472,-0.1],...
    'Rotation',0);

xlabel({'f \rightarrow','[Hz]'},...
    'FontName',fontName,...
    'FontSize',14);

annotation('arrow',[0.3535 0.3535],...
    [0.43 0.435]);

y_lim_5 = [0 1];
x_lim_5 = [0 2*f_m];
set(ax5,...
    'Box','off',...
    'XAxisLocation','origin',...
    'YMinorTick','off',...
    'XMinorTick','off',...
    'TickDir','both',...
    'TickLabelInterpreter','tex',...
    'FontSize',12,...
    'YAxisLocation','origin',...
    'XLim',x_lim_5,...
    'Ylim', y_lim_5,...
    'XTick',[0 f_m],...
    'XTickLabel',{'0';'f_{m}'},...
    'YTick',[]);

[Peak, PeakIdx] = findpeaks(mix_frequency);
for i=4:numel(Peak)
    text(f(PeakIdx(i)), Peak(i), sprintf('%6.0fx10^3', f(PeakIdx(i))/1000))
end

ax5.XAxis.Label.Units='normalized';
ax5.XAxis.Label.Position = [0.98 0.15 0];
ax5.XAxis.SecondaryLabel.Units='normalized';
ax5.XAxis.SecondaryLabel.Position = [0.999 -0.029 0];

ax5.Position = FillAxesPos(ax5,1.1);
pos_5 = ax5.Position;
ax5.Position = [pos_5(1) pos_5(2)-0.021 pos_5(3) pos_5(4)*1.05];

%% Plot 6 (Demodulated signal frequency spectrum)
ax6 = subplot(subplot_row,subplot_col,6);
hold on;

p6 = stem(f,demodulated_frequency,'o',...
    'Color',pastel_blue,... 
    'DisplayName','|Y(f)|',...
	'LineStyle','-',...
	'LineWidth',line_thick,...
    'MarkerSize',marker_size,...
    'MarkerFaceColor',nice_red(1:3));
hold on

% Title and Annotations
if ~export_on
    t6 = title({strcat("Demodulated signal frequency ", p6.DisplayName); " "});
end

% Axes and labels
ylabel(p6.DisplayName,...
    'FontName',fontName,...
    'FontSize',14);
xlabel({'f \rightarrow','[Hz]'},...
    'FontName',fontName,...
    'FontSize',14);

annotation('arrow',[0.77 0.77],...
    [0.426 0.4407]);

y_lim_6 = [0 max(demodulated_frequency)]*1.2;
x_lim_6 = [-1.5e3 1.5e3];
set(ax6,...
    'Box','off',...
    'XAxisLocation','origin',...
    'YMinorTick','off',...
    'XMinorTick','off',...
    'TickDir','both',...
    'TickLabelInterpreter','tex',...
    'FontSize',12,...
    'YAxisLocation','origin',...
    'XLim',x_lim_6,...
    'Ylim', y_lim_6,...
    'XTick',[-f_m 0 f_m],...
    'YTick',[]);
ax6.XAxis.Label.Units='normalized';
ax6.XAxis.Label.Position = [0.98 0.1 0];
ax6.XAxis.SecondaryLabel.Units='normalized';
ax6.XAxis.SecondaryLabel.Position = [0.999 -0.29 0];
ax6.Position = FillAxesPos(ax6,1.1);

hold off

set(fig1,'visible','on');
drawnow;

%% Export images
% if export_on
    fNew = figure;
    set(fNew,'numbertitle','off',...
        'name','Lab 3 - Exercise 1b',...
        'Color','white',...
        'Units','normalized');

    clf(fNew);     
    hNew = copyobj(ax2, fNew);
    set(hNew, 'pos', [0.1 0.05 0.85 0.9])
    annotation('arrow',[0.1 0.1],[0.95 0.955]);
%     export_fig ../Report/images/Exercise1b_B_mixed.eps  -eps ;

    clf(fNew);     
    hNew = copyobj(ax5, fNew);
    set(hNew, 'pos', [0.1 0.05 0.85 0.9])
    annotation('arrow',[0.1 0.1],[0.95 0.955]);
%     export_fig ../Report/images/Exercise1b_E_mixed.eps  -eps ;
    
%     delete(fNew);
% end